### ISSUE TITLE
Questions about the docker image tests are run in.

### ISSUE THREAD

**Issue by verdverm** [cue-sh/unity#61]
- what binaries / tools are available within the image? (was hoping to use git, but am getting errors with `exec git ...`
- where is the Dockerfile, is it in another repo? (I am unable to locate it to answer the previous myself)

**Comment by myitcv** [comment]
This question is effectively #40 

* The docker image currently used is https://github.com/cue-sh/unity/blob/eb25346d70261e1cf94f9500496c9a809b3b8945/cmd/unity/cmd/test.go#L47
* That derives from https://github.com/cue-sh/unity-docker, specifically https://github.com/cue-sh/unity-docker/blob/72a5a022b434a768e8c5ae5be7082d780211accd/Dockerfile#L5

I'd suggest we continue the conversation in #40.
